In [2]:
import os
import pandas as pd
import datetime
import re
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# Function to list all chat files in the directory structure
def list_chat_files(date_directory):
    chat_files = []
    for date_folder in os.listdir(date_directory):
        date_path = os.path.join(date_directory, date_folder)
        if os.path.isdir(date_path):
            for team_folder in os.listdir(date_path):
                team_path = os.path.join(date_path, team_folder)
                if os.path.isdir(team_path):
                    for person_folder in os.listdir(team_path):
                        person_path = os.path.join(team_path, person_folder)
                        if os.path.isdir(person_path):
                            for file in os.listdir(person_path):
                                if file.endswith('.txt'):
                                    chat_files.append(os.path.join(person_path, file))
    return chat_files

def parse_chat_file(file_path):
    chat_data = []
    today_minus_one = datetime.datetime.now().date() - datetime.timedelta(days=1)

    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            message_match = re.match(r'(\d{2}/\d{2}/\d{2}, \d{1,2}:\d{2} [ap]m) - (.*?): (.*)', line)
            system_match = re.match(r'(\d{2}/\d{2}/\d{2}, \d{1,2}:\d{2} [ap]m) - (.*)', line)
            if message_match:
                date_time_str, sender, message = message_match.groups()
            elif system_match:
                date_time_str, info = system_match.groups()
                sender = None
            else:
                continue

            date_time = pd.to_datetime(date_time_str, format='%d/%m/%y, %I:%M %p')

            # Comparing parsed date with today - 1
            if date_time.date() != today_minus_one:
                continue

            # Adjusted logic to check for numeric sender (phone number)
            is_person = sender is not None and re.match(r'^[+\d\s-]+$', sender) is None  # True if sender is NOT purely numeric

            chat_data.append((date_time, sender, is_person))
    return chat_data

# Function to create a template dataframe
def create_template_dataframe():
    times = [datetime.datetime(2000, 1, 1, 0, 0) + datetime.timedelta(minutes=1 * i) for i in range(1440)]
    intervals = [time.strftime('%I:%M %p') for time in times]
    df = pd.DataFrame(index=intervals)
    return df

def populate_dataframe(df, parsed_data, start_column_index):
    new_columns = {}  # Dictionary to hold new data before concatenation

    for entry in parsed_data:
        date_time, sender, is_person = entry
        interval_index = min((date_time.hour * 60 + date_time.minute) // 1, 1439)
        interval = df.index[interval_index]

        # Initialize columns in new_columns dictionary if not exist
        if (start_column_index not in new_columns):
            new_columns[start_column_index] = pd.Series(0, index=df.index)
        if (start_column_index + 1 not in new_columns):
            new_columns[start_column_index + 1] = pd.Series(0, index=df.index)

        # Populate the new_columns dictionary
        if is_person:
            new_columns[start_column_index].at[interval] = 1
        else:
            new_columns[start_column_index + 1].at[interval] = 1
    print(f"DataFrame after concatenation: {df.head()}")
    # Concatenate new columns to the DataFrame at once
    df = pd.concat([df, pd.DataFrame(new_columns)], axis=1)

    return df, start_column_index + 2

def process_person_chats(chat_files):
    dataframes = {}
    for file in chat_files:
        parts = file.split(os.sep)
        date_folder, person = parts[-4], parts[-2]

        try:
            expected_date = pd.to_datetime(date_folder).date()
        except ValueError:
            continue

        key = f"{expected_date.strftime('%Y-%m-%d')}_{person}"

        if key not in dataframes:
            dataframes[key] = create_template_dataframe()
            start_column_index = 0
        else:
            if not dataframes[key].columns.empty:
                start_column_index = max(dataframes[key].columns) + 1
            else:
                start_column_index = 0

        # Updated call to parse_chat_file
        parsed_data = parse_chat_file(file)
        dataframes[key], start_column_index = populate_dataframe(dataframes[key], parsed_data, start_column_index)

    return dataframes
print("analysis complete. Generating Graphs...")
# Function to create bar and trend graphs for each person
def create_graphs(df, person_identifier, base_directory):
    graph_directory = os.path.join(base_directory, "Graphs")
    os.makedirs(graph_directory, exist_ok=True)

    # Sum the values across all even columns for each minute
    person_chat_activity = df.iloc[:, 0::2].sum(axis=1)
    trend_data = df.iloc[:, 1::2].sum(axis=1)

    print(f"Generating graph for {person_identifier}")  # Debug line
    fig, ax = plt.subplots(figsize=(20, 10))  # Increase figure size

    # Plotting the bar graph for the person's total chat activity
    ax.bar(df.index, person_chat_activity, color='deepskyblue', width=1, label=f'Person {person_identifier}')  # Wider bars

    # Plotting the trend line for system messages
    ax.plot(df.index, trend_data, color='black', linewidth=0.2, label='Trend')

    # Rotate x-axis labels to prevent overlap and increase label font sizes
    plt.xticks(rotation=90, fontsize=8)
    plt.yticks(fontsize=10)
    
    # Set x-axis major ticks to every 4th label to ensure they don't overlap
    ax.xaxis.set_major_locator(ticker.MultipleLocator(4))
    ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: df.index[int(x)] if int(x) < len(df.index) else ''))

    # Set y-axis dynamic range based on the maximum chat activity with a buffer
    max_chats = max(person_chat_activity.max(), trend_data.max())
    ax.set_ylim(0, max_chats + 5)  # Adjust y-axis limit based on maximum chat activity plus a buffer

    # Increasing font size for labels and title
    ax.set_xlabel('Time', fontsize=12)
    ax.set_ylabel('Number of Chats', fontsize=12)
    ax.set_title(f'Chat Activity for {person_identifier}', fontsize=14)
    ax.legend()

    # Saving the graph
    graph_file_name = f"{person_identifier}.png"
    plt.savefig(os.path.join(graph_directory, graph_file_name), format='png', dpi=300, bbox_inches='tight')  # Save with tight bounding box
    print(f"Graph saved as {graph_file_name}")  # Debug line

    plt.close(fig)



# Main script
date_directory = "C:\\Users\\mauriceyeng\\Python\\Daily-Reports\\Test\\filtered_chats"
chat_files = list_chat_files(date_directory)
person_dataframes = process_person_chats(chat_files)

# Generating graphs for each DataFrame
for person_identifier, df in person_dataframes.items():
    create_graphs(df, person_identifier, date_directory)

analysis complete. Generating Graphs...
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  56  57  58  59  60  61  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          62  63  64  65
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 66 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  58  59  60  61  62  63  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          64  65  66  67
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 68 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  60  61  62  63  64  65  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          66  67  68  69
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 70 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  62  63  64  65  66  67  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          68  69  70  71
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 72 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  64  65  66  67  68  69  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          70  71  72  73
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 74 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  66  67  68  69  70  71  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          72  73  74  75
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 76 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  68  69  70  71  72  73  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          74  75  76  77
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 78 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  70  71  72  73  74  75  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          76  77  78  79
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 80 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  72  73  74  75  76  77  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          78  79  80  81
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 82 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  74  75  76  77  78  79  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          80  81  82  83
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 84 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  76  77  78  79  80  81  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          82  83  84  85
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 86 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  78  79  80  81  82  83  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          84  85  86  87
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 88 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  80  81  82  83  84  85  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          86  87  88  89
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 90 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  82  83  84  85  86  87  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          88  89  90  91
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 92 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          90  91  92  93
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 94 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  86  87  88  89  90  91  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          92  93  94  95
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 96 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  88  89  90  91  92  93  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          94  95  96  97
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 98 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          96  97  98  99
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 100 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  92   93   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          94   95   96   97   98   99   100  101
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 102 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  94   95   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          96   97   98   99   100  101  102  103
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 104 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  96   97   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          98   99   100  101  102  103  104  105
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 106 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  98   99   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          100  101  102  103  104  105  106  107
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 108 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  100  101  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          102  103  104  105  106  107  108  109
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 110 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  102  103  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          104  105  106  107  108  109  110  111
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 112 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  104  105  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          106  107  108  109  110  111  112  113
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 114 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  106  107  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          108  109  110  111  112  113  114  115
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 116 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  108  109  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          110  111  112  113  114  115  116  117
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 118 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  110  111  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          112  113  114  115  116  117  118  119
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 120 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  112  113  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          114  115  116  117  118  119  120  121
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 122 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  114  115  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          116  117  118  119  120  121  122  123
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 124 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  116  117  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          118  119  120  121  122  123  124  125
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 126 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  118  119  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          120  121  122  123  124  125  126  127
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 128 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  120  121  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          122  123  124  125  126  127  128  129
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 130 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  122  123  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          124  125  126  127  128  129  130  131
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 132 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  124  125  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          126  127  128  129  130  131  132  133
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 134 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  126  127  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          128  129  130  131  132  133  134  135
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 136 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  56  57  58  59  60  61  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          62  63  64  65
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 66 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  58  59  60  61  62  63  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          64  65  66  67
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 68 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  60  61  62  63  64  65  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          66  67  68  69
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 70 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  62  63  64  65  66  67  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          68  69  70  71
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 72 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  64  65  66  67  68  69  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          70  71  72  73
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 74 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  66  67  68  69  70  71  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          72  73  74  75
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 76 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  68  69  70  71  72  73  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          74  75  76  77
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 78 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  70  71  72  73  74  75  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          76  77  78  79
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 80 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  72  73  74  75  76  77  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          78  79  80  81
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 82 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  74  75  76  77  78  79  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          80  81  82  83
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 84 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  76  77  78  79  80  81  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          82  83  84  85
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 86 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  78  79  80  81  82  83  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          84  85  86  87
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 88 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  80  81  82  83  84  85  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          86  87  88  89
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 90 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  82  83  84  85  86  87  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          88  89  90  91
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 92 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          90  91  92  93
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 94 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  86  87  88  89  90  91  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          92  93  94  95
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 96 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  88  89  90  91  92  93  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          94  95  96  97
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 98 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          96  97  98  99
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 100 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  92   93   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          94   95   96   97   98   99   100  101
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 102 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  94   95   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          96   97   98   99   100  101  102  103
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 104 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  56  57  58  59  60  61  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          62  63  64  65
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 66 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  58  59  60  61  62  63  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          64  65  66  67
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 68 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  60  61  62  63  64  65  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          66  67  68  69
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 70 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  62  63  64  65  66  67  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          68  69  70  71
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 72 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  64  65  66  67  68  69  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          70  71  72  73
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 74 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  66  67  68  69  70  71  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          72  73  74  75
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 76 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  68  69  70  71  72  73  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          74  75  76  77
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 78 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  70  71  72  73  74  75  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          76  77  78  79
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 80 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  72  73  74  75  76  77  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          78  79  80  81
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 82 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  74  75  76  77  78  79  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          80  81  82  83
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 84 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  76  77  78  79  80  81  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          82  83  84  85
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 86 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  78  79  80  81  82  83  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          84  85  86  87
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 88 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  80  81  82  83  84  85  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          86  87  88  89
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 90 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  82  83  84  85  86  87  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          88  89  90  91
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 92 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          90  91  92  93
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 94 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  86  87  88  89  90  91  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          92  93  94  95
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 96 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  88  89  90  91  92  93  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          94  95  96  97
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 98 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  88  89  90  91  92  93  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          94  95  96  97
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 98 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          96  97  98  99
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 100 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  92   93   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          94   95   96   97   98   99   100  101
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 102 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  94   95   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          96   97   98   99   100  101  102  103
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 104 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  96   97   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          98   99   100  101  102  103  104  105
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 106 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  98   99   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          100  101  102  103  104  105  106  107
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 108 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  100  101  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          102  103  104  105  106  107  108  109
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 110 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  102  103  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          104  105  106  107  108  109  110  111
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 112 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  104  105  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          106  107  108  109  110  111  112  113
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 114 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  106  107  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          108  109  110  111  112  113  114  115
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 116 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  108  109  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          110  111  112  113  114  115  116  117
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 118 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  110  111  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          112  113  114  115  116  117  118  119
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 120 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  112  113  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          114  115  116  117  118  119  120  121
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 122 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  114  115  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          116  117  118  119  120  121  122  123
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 124 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  116  117  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          118  119  120  121  122  123  124  125
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 126 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  118  119  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          120  121  122  123  124  125  126  127
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 128 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  120  121  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          122  123  124  125  126  127  128  129
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 130 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  122  123  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          124  125  126  127  128  129  130  131
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 132 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  124  125  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          126  127  128  129  130  131  132  133
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 134 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  126  127  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          128  129  130  131  132  133  134  135
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 136 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  128  129  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          130  131  132  133  134  135  136  137
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 138 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  130  131  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          132  133  134  135  136  137  138  139
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 140 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  132  133  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          134  135  136  137  138  139  140  141
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 142 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  134  135  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          136  137  138  139  140  141  142  143
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 144 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  136  137  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          138  139  140  141  142  143  144  145
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 146 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  138  139  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          140  141  142  143  144  145  146  147
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 148 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  140  141  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          142  143  144  145  146  147  148  149
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 150 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  142  143  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          144  145  146  147  148  149  150  151
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 152 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  144  145  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          146  147  148  149  150  151  152  153
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 154 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  146  147  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          148  149  150  151  152  153  154  155
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 156 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  148  149  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          150  151  152  153  154  155  156  157
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 158 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  150  151  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          152  153  154  155  156  157  158  159
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 160 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  56  57  58  59  60  61  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          62  63  64  65
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 66 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  58  59  60  61  62  63  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          64  65  66  67
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 68 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  60  61  62  63  64  65  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          66  67  68  69
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 70 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  62  63  64  65  66  67  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          68  69  70  71
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 72 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  64  65  66  67  68  69  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          70  71  72  73
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 74 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  66  67  68  69  70  71  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          72  73  74  75
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 76 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  68  69  70  71  72  73  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          74  75  76  77
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 78 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  70  71  72  73  74  75  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          76  77  78  79
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 80 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  72  73  74  75  76  77  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          78  79  80  81
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 82 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  74  75  76  77  78  79  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          80  81  82  83
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 84 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  76  77  78  79  80  81  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          82  83  84  85
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 86 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  78  79  80  81  82  83  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          84  85  86  87
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 88 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  80  81  82  83  84  85  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          86  87  88  89
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 90 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  82  83  84  85  86  87  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          88  89  90  91
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 92 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          90  91  92  93
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 94 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  86  87  88  89  90  91  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          92  93  94  95
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 96 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  88  89  90  91  92  93  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          94  95  96  97
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 98 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          96  97  98  99
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 100 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  92   93   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          94   95   96   97   98   99   100  101
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 102 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  94   95   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          96   97   98   99   100  101  102  103
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 104 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  96   97   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          98   99   100  101  102  103  104  105
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 106 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  98   99   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          100  101  102  103  104  105  106  107
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 108 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  100  101  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          102  103  104  105  106  107  108  109
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 110 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  102  103  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          104  105  106  107  108  109  110  111
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 112 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  104  105  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          106  107  108  109  110  111  112  113
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 114 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  106  107  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          108  109  110  111  112  113  114  115
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 116 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  108  109  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          110  111  112  113  114  115  116  117
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 118 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  110  111  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          112  113  114  115  116  117  118  119
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 120 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  112  113  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          114  115  116  117  118  119  120  121
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 122 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  114  115  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          116  117  118  119  120  121  122  123
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 124 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  116  117  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          118  119  120  121  122  123  124  125
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 126 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  118  119  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          120  121  122  123  124  125  126  127
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 128 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  120  121  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          122  123  124  125  126  127  128  129
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 130 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  122  123  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          124  125  126  127  128  129  130  131
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 132 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  124  125  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          126  127  128  129  130  131  132  133
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 134 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  126  127  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          128  129  130  131  132  133  134  135
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 136 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  128  129  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          130  131  132  133  134  135  136  137
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 138 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  130  131  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          132  133  134  135  136  137  138  139
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 140 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  132  133  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          134  135  136  137  138  139  140  141
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 142 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  134  135  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          136  137  138  139  140  141  142  143
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 144 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  136  137  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          138  139  140  141  142  143  144  145
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 146 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  138  139  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          140  141  142  143  144  145  146  147
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 148 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  140  141  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          142  143  144  145  146  147  148  149
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 150 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  142  143  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          144  145  146  147  148  149  150  151
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 152 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  144  145  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          146  147  148  149  150  151  152  153
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 154 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  146  147  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          148  149  150  151  152  153  154  155
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 156 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  148  149  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          150  151  152  153  154  155  156  157
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 158 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  150  151  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          152  153  154  155  156  157  158  159
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 160 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  152  153  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          154  155  156  157  158  159  160  161
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 162 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  154  155  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          156  157  158  159  160  161  162  163
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 164 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  156  157  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          158  159  160  161  162  163  164  165
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 166 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  158  159  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          160  161  162  163  164  165  166  167
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 168 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  160  161  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          162  163  164  165  166  167  168  169
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 170 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  162  163  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          164  165  166  167  168  169  170  171
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 172 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  164  165  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          166  167  168  169  170  171  172  173
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 174 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  166  167  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          168  169  170  171  172  173  174  175
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 176 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  168  169  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          170  171  172  173  174  175  176  177
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 178 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  170  171  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          172  173  174  175  176  177  178  179
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 180 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  172  173  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          174  175  176  177  178  179  180  181
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 182 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  174  175  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          176  177  178  179  180  181  182  183
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 184 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  176  177  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          178  179  180  181  182  183  184  185
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 186 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  178  179  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          180  181  182  183  184  185  186  187
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 188 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  180  181  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          182  183  184  185  186  187  188  189
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 190 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  182  183  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          184  185  186  187  188  189  190  191
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 192 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  184  185  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          186  187  188  189  190  191  192  193
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 194 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  186  187  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          188  189  190  191  192  193  194  195
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 196 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  188  189  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          190  191  192  193  194  195  196  197
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 198 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  190  191  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          192  193  194  195  196  197  198  199
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 200 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  192  193  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          194  195  196  197  198  199  200  201
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 202 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  194  195  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          196  197  198  199  200  201  202  203
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 204 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  196  197  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          198  199  200  201  202  203  204  205
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 206 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  198  199  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          200  201  202  203  204  205  206  207
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 208 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  200  201  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          202  203  204  205  206  207  208  209
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 210 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  202  203  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          204  205  206  207  208  209  210  211
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 212 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  204  205  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          206  207  208  209  210  211  212  213
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 214 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  206  207  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          208  209  210  211  212  213  214  215
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 216 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  208  209  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          210  211  212  213  214  215  216  217
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 218 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  210  211  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          212  213  214  215  216  217  218  219
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 220 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  212  213  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          214  215  216  217  218  219  220  221
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 222 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  214  215  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          216  217  218  219  220  221  222  223
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 224 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  216  217  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          218  219  220  221  222  223  224  225
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 226 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  218  219  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          220  221  222  223  224  225  226  227
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 228 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  220  221  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          222  223  224  225  226  227  228  229
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 230 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  222  223  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          224  225  226  227  228  229  230  231
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 232 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  224  225  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          226  227  228  229  230  231  232  233
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 234 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  226  227  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          228  229  230  231  232  233  234  235
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 236 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  228  229  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          230  231  232  233  234  235  236  237
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 238 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  230  231  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          232  233  234  235  236  237  238  239
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 240 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  232  233  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          234  235  236  237  238  239  240  241
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 242 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  234  235  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          236  237  238  239  240  241  242  243
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 244 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  236  237  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          238  239  240  241  242  243  244  245
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 246 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  238  239  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          240  241  242  243  244  245  246  247
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 248 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  240  241  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          242  243  244  245  246  247  248  249
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 250 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  242  243  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          244  245  246  247  248  249  250  251
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 252 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  244  245  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          246  247  248  249  250  251  252  253
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 254 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  246  247  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          248  249  250  251  252  253  254  255
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 256 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  248  249  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          250  251  252  253  254  255  256  257
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 258 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  250  251  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          252  253  254  255  256  257  258  259
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 260 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  252  253  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          254  255  256  257  258  259  260  261
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 262 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  254  255  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          256  257  258  259  260  261  262  263
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 264 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  256  257  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          258  259  260  261  262  263  264  265
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 266 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  258  259  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          260  261  262  263  264  265  266  267
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 268 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  260  261  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          262  263  264  265  266  267  268  269
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 270 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  262  263  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          264  265  266  267  268  269  270  271
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 272 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  264  265  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          266  267  268  269  270  271  272  273
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 274 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  266  267  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          268  269  270  271  272  273  274  275
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 276 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  268  269  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          270  271  272  273  274  275  276  277
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 278 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  270  271  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          272  273  274  275  276  277  278  279
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 280 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  272  273  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          274  275  276  277  278  279  280  281
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 282 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  274  275  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          276  277  278  279  280  281  282  283
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 284 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  56  57  58  59  60  61  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          62  63  64  65
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 66 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  58  59  60  61  62  63  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          64  65  66  67
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 68 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  60  61  62  63  64  65  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          66  67  68  69
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 70 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  62  63  64  65  66  67  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          68  69  70  71
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 72 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  64  65  66  67  68  69  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          70  71  72  73
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 74 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  66  67  68  69  70  71  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          72  73  74  75
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 76 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  68  69  70  71  72  73  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          74  75  76  77
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 78 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  70  71  72  73  74  75  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          76  77  78  79
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 80 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  72  73  74  75  76  77  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          78  79  80  81
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 82 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  74  75  76  77  78  79  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          80  81  82  83
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 84 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  76  77  78  79  80  81  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          82  83  84  85
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 86 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  78  79  80  81  82  83  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          84  85  86  87
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 88 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  80  81  82  83  84  85  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          86  87  88  89
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 90 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  82  83  84  85  86  87  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          88  89  90  91
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 92 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  84  85  86  87  88  89  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          90  91  92  93
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 94 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  86  87  88  89  90  91  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          92  93  94  95
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 96 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  88  89  90  91  92  93  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          94  95  96  97
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 98 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          96  97  98  99
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 100 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  92   93   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          94   95   96   97   98   99   100  101
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 102 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  94   95   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          96   97   98   99   100  101  102  103
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 104 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  96   97   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          98   99   100  101  102  103  104  105
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 106 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  98   99   \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          100  101  102  103  104  105  106  107
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 108 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  100  101  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          102  103  104  105  106  107  108  109
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 110 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  102  103  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          104  105  106  107  108  109  110  111
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 112 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  104  105  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          106  107  108  109  110  111  112  113
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 114 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  106  107  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          108  109  110  111  112  113  114  115
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 116 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  108  109  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          110  111  112  113  114  115  116  117
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 118 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  110  111  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          112  113  114  115  116  117  118  119
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 120 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  112  113  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          114  115  116  117  118  119  120  121
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 122 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  114  115  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          116  117  118  119  120  121  122  123
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 124 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  116  117  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          118  119  120  121  122  123  124  125
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 126 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  118  119  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          120  121  122  123  124  125  126  127
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 128 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  120  121  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          122  123  124  125  126  127  128  129
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 130 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  122  123  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          124  125  126  127  128  129  130  131
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 132 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  124  125  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          126  127  128  129  130  131  132  133
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 134 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  126  127  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          128  129  130  131  132  133  134  135
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 136 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  128  129  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          130  131  132  133  134  135  136  137
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 138 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  130  131  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          132  133  134  135  136  137  138  139
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 140 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  132  133  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          134  135  136  137  138  139  140  141
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 142 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  134  135  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          136  137  138  139  140  141  142  143
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 144 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  136  137  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          138  139  140  141  142  143  144  145
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 146 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  138  139  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          140  141  142  143  144  145  146  147
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 148 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  140  141  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          142  143  144  145  146  147  148  149
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 150 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  142  143  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          144  145  146  147  148  149  150  151
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 152 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  144  145  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          146  147  148  149  150  151  152  153
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 154 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  146  147  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          148  149  150  151  152  153  154  155
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 156 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  148  149  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          150  151  152  153  154  155  156  157
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 158 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  150  151  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          152  153  154  155  156  157  158  159
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 160 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  152  153  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          154  155  156  157  158  159  160  161
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 162 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  154  155  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          156  157  158  159  160  161  162  163
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 164 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  156  157  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          158  159  160  161  162  163  164  165
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 166 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  158  159  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          160  161  162  163  164  165  166  167
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 168 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  160  161  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          162  163  164  165  166  167  168  169
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 170 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  162  163  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          164  165  166  167  168  169  170  171
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 172 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  164  165  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          166  167  168  169  170  171  172  173
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 174 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  166  167  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          168  169  170  171  172  173  174  175
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 176 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  168  169  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          170  171  172  173  174  175  176  177
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 178 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  170  171  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          172  173  174  175  176  177  178  179
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 180 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  172  173  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          174  175  176  177  178  179  180  181
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 182 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  174  175  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          176  177  178  179  180  181  182  183
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 184 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  176  177  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          178  179  180  181  182  183  184  185
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 186 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  178  179  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          180  181  182  183  184  185  186  187
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 188 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  180  181  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          182  183  184  185  186  187  188  189
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 190 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  182  183  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          184  185  186  187  188  189  190  191
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 192 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  184  185  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          186  187  188  189  190  191  192  193
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 194 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  186  187  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          188  189  190  191  192  193  194  195
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 196 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  188  189  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          190  191  192  193  194  195  196  197
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 198 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  190  191  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          192  193  194  195  196  197  198  199
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 200 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  192  193  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          194  195  196  197  198  199  200  201
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 202 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  194  195  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          196  197  198  199  200  201  202  203
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 204 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  196  197  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          198  199  200  201  202  203  204  205
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 206 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  198  199  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          200  201  202  203  204  205  206  207
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 208 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  200  201  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          202  203  204  205  206  207  208  209
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 210 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  202  203  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          204  205  206  207  208  209  210  211
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 212 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  204  205  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          206  207  208  209  210  211  212  213
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 214 columns]

DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  206  207  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          208  209  210  211  212  213  214  215
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 216 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  208  209  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          210  211  212  213  214  215  216  217
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 218 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  210  211  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          212  213  214  215  216  217  218  219
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 220 columns]
DataFrame after concatenation:           0    1    2    3    4    5    6    7    8    9    ...  212  213  \
12:00 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:01 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:02 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:03 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0
12:04 AM    0    0    0    0    0    0    0    0    0    0  ...    0    0

          214  215  216  217  218  219  220  221
12:00 AM    0    0    0    0    0    0    0    0
12:01 AM    0    0    0    0    0    0    0    0
12:02 AM    0    0    0    0    0    0    0    0
12:03 AM    0    0    0    0    0    0    0    0
12:04 AM    0    0    0    0    0    0    0    0

[5 rows x 222 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
DataFrame after concatenation:           0  1
12:00 AM  0  0
12:01 AM  0  0
12:02 AM  0  0
12:03 AM  0  0
12:04 AM  0  0
DataFrame after concatenation:           0  1  2  3
12:00 AM  0  0  0  0
12:01 AM  0  0  0  0
12:02 AM  0  0  0  0
12:03 AM  0  0  0  0
12:04 AM  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5
12:00 AM  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7
12:00 AM  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0  1  2  3  4  5  6  7  8  9
12:00 AM  0  0  0  0  0  0  0  0  0  0
12:01 AM  0  0  0  0  0  0  0  0  0  0
12:02 AM  0  0  0  0  0  0  0  0  0  0
12:03 AM  0  0  0  0  0  0  0  0  0  0
12:04 AM  0  0  0  0  0  0  0  0  0  0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17
12:00 AM   0
12:01 AM   0
12:02 AM   0
12:03 AM   0
12:04 AM   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
12:00 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

          17  18  19
12:00 AM   0   0   0
12:01 AM   0   0   0
12:02 AM   0   0   0
12:03 AM   0   0   0
12:04 AM   0   0   0
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          18  19  20  21
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 22 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          20  21  22  23
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 24 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  16  17  18  19  20  21  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          22  23  24  25
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 26 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          24  25  26  27
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 28 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          26  27  28  29
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 30 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          28  29  30  31
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 32 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  24  25  26  27  28  29  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          30  31  32  33
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 34 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  26  27  28  29  30  31  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          32  33  34  35
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 36 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  28  29  30  31  32  33  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          34  35  36  37
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 38 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  30  31  32  33  34  35  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          36  37  38  39
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 40 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          38  39  40  41
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 42 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  34  35  36  37  38  39  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          40  41  42  43
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 44 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  36  37  38  39  40  41  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          42  43  44  45
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 46 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  38  39  40  41  42  43  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          44  45  46  47
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 48 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          46  47  48  49
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 50 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  42  43  44  45  46  47  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          48  49  50  51
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 52 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  44  45  46  47  48  49  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          50  51  52  53
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 54 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  46  47  48  49  50  51  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          52  53  54  55
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 56 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          54  55  56  57
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 58 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  50  51  52  53  54  55  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          56  57  58  59
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 60 columns]

DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  52  53  54  55  56  57  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          58  59  60  61
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 62 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  54  55  56  57  58  59  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          60  61  62  63
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 64 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  56  57  58  59  60  61  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          62  63  64  65
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 66 columns]
DataFrame after concatenation:           0   1   2   3   4   5   6   7   8   9   ...  58  59  60  61  62  63  \
12:00 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:01 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:02 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:03 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0
12:04 AM   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0

          64  65  66  67
12:00 AM   0   0   0   0
12:01 AM   0   0   0   0
12:02 AM   0   0   0   0
12:03 AM   0   0   0   0
12:04 AM   0   0   0   0

[5 rows x 68 columns]
DataFrame after concatenation: Empty DataFrame
Columns: []
Index: [12:00 AM, 12:01 AM, 12:02 AM, 12:03 AM, 12:04 AM]
Generating graph for 2023-11-28_Arshita
Graph saved as 2023-11-28_Arshita.png
Generating graph for 2023-11-28_Austin#276
Graph saved as 2023-11-28_Austin#276.png
Generating graph for 2023-11-28_Harmehak
Graph saved as 2023-11-28_Harmehak.png
Generating graph for 2023-11-28_Pallika Edoofa
Graph saved as 2023-11-28_Pallika Edoofa.png
Generating graph for 2023-11-28_Sagar
Graph saved as 2023-11-28_Sagar.png
Generating graph for 2023-11-28_Sahil Edoofa
Graph saved as 2023-11-28_Sahil Edoofa.png
Generating graph for 2023-11-28_Shashwat Edoofa 2
Graph saved as 2023-11-28_Shashwat Edoofa 2.png
Generating graph for 2023-11-28_Shubham Madhwal
Graph saved as 2023-11-28_Shubham Madhwal.png
Generating graph for 2023-11-28_Tushti
Graph saved as 2023-11-28_Tushti.png